# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fit Vector Autoregressive (VAR) Model Parameters
#' using Lasso Regularization with Lambda Search
#'
#' @author Ivan Jacob Agaloos Pesigan
#'
#' @param lambdas Numeric vector.
#'   Lasso hyperparameter.
#'   The regularization strength controlling the sparsity.
#' @param crit Character string.
#'   Information criteria to use.
#'   Valid values include `"aic"`, `"bic"`, and `"ebic"`.
#' @inheritParams FitVARLasso
#'
#' @return Matrix of estimated autoregressive
#'   and cross-regression coefficients.
#'
#' @examples
#' YStd <- StdMat(dat_p2_yx$Y)
#' XStd <- StdMat(dat_p2_yx$X[, -1]) # remove the constant column
#' lambdas <- LambdaSeq(
#'   YStd = YStd,
#'   XStd = XStd,
#'   n_lambdas = 100
#' )
#' FitVARLassoSearch(
#'   YStd = YStd,
#'   XStd = XStd,
#'   lambdas = lambdas,
#'   crit = "ebic",
#'   max_iter = 1000,
#'   tol = 1e-5
#' )
#'
#' @family Fitting Autoregressive Model Functions
#' @keywords fitAutoReg fit
#' @export
FitVARLassoSearch <- function(YStd, XStd, lambdas, crit, max_iter, tol) {
    .Call(`_fitAutoReg_FitVARLassoSearch`, YStd, XStd, lambdas, crit, max_iter, tol)
}

#' Fit Vector Autoregressive (VAR) Model Parameters
#' using Lasso Regularization
#'
#' This function estimates the parameters of a VAR model
#' using the Lasso regularization method
#' with cyclical coordinate descent.
#' The Lasso method is used to estimate the autoregressive
#' and cross-regression coefficients with sparsity.
#'
#' @author Ivan Jacob Agaloos Pesigan
#'
#' @param YStd Numeric matrix.
#'   Matrix of standardized dependent variables (Y).
#' @param XStd Numeric matrix.
#'   Matrix of standardized predictors (X).
#'   `XStd` should not include a vector of ones in column one.
#' @param lambda Numeric.
#'   Lasso hyperparameter.
#'   The regularization strength controlling the sparsity.
#' @param max_iter Integer.
#'   The maximum number of iterations
#'   for the coordinate descent algorithm
#'   (e.g., `max_iter = 10000`).
#' @param tol Numeric.
#'   Convergence tolerance.
#'   The algorithm stops when the change in coefficients
#'   between iterations is below this tolerance
#'   (e.g., `tol = 1e-5`).
#'
#' @return Matrix of estimated autoregressive
#'   and cross-regression coefficients.
#'
#' @examples
#' YStd <- StdMat(dat_p2_yx$Y)
#' XStd <- StdMat(dat_p2_yx$X[, -1]) # remove the constant column
#' lambda <- 73.90722
#' FitVARLasso(
#'   YStd = YStd,
#'   XStd = XStd,
#'   lambda = lambda,
#'   max_iter = 10000,
#'   tol = 1e-5
#' )
#'
#' @details
#' The [fitAutoReg::FitVARLasso()] function estimates the parameters
#' of a Vector Autoregressive (VAR) model
#' using the Lasso regularization method.
#' Given the input matrices `YStd` and `XStd`,
#' where `YStd` is the matrix of standardized dependent variables,
#' and `XStd` is the matrix of standardized predictors,
#' the function computes the autoregressive and cross-regression coefficients
#' of the VAR model with sparsity induced by the Lasso regularization.
#'
#' The steps involved in estimating the VAR model parameters
#' using Lasso are as follows:
#'
#' - **Initialization**: The function initializes the coefficient matrix
#'   `beta` with OLS estimates.
#'   The `beta` matrix will store the estimated autoregressive and
#'   cross-regression coefficients.
#' - **Coordinate Descent Loop**: The function performs
#'   the cyclical coordinate descent algorithm
#'   to estimate the coefficients iteratively.
#'   The loop iterates `max_iter` times,
#'   or until convergence is achieved.
#'   The outer loop iterates over the predictor variables
#'   (columns of `XStd`),
#'   while the inner loop iterates over the outcome variables
#'   (columns of `YStd`).
#' - **Coefficient Update**: For each predictor variable (column of `XStd`),
#'   the function iteratively updates the corresponding column of `beta`
#'   using the coordinate descent algorithm with L1 norm regularization
#'   (Lasso).
#'   The update involves calculating the soft-thresholded value `c`,
#'   which encourages sparsity in the coefficients.
#'   The algorithm continues until the change in coefficients
#'   between iterations is below the specified tolerance `tol`
#'   or when the maximum number of iterations is reached.
#' - **Convergence Check**: The function checks for convergence
#'   by comparing the current `beta`
#'   matrix with the previous iteration's `beta_old`.
#'   If the maximum absolute difference between `beta` and `beta_old`
#'   is below the tolerance `tol`,
#'   the algorithm is considered converged, and the loop exits.
#'
#' @family Fitting Autoregressive Model Functions
#' @keywords fitAutoReg fit
#' @export
FitVARLasso <- function(YStd, XStd, lambda, max_iter, tol) {
    .Call(`_fitAutoReg_FitVARLasso`, YStd, XStd, lambda, max_iter, tol)
}

#' Fit Vector Autoregressive (VAR) Model Parameters
#' using Ordinary Least Squares (OLS)
#'
#' This function estimates the parameters of a VAR model
#' using the Ordinary Least Squares (OLS) method.
#' The OLS method is used to estimate the autoregressive
#' and cross-regression coefficients.
#'
#' @author Ivan Jacob Agaloos Pesigan
#'
#' @param Y Numeric matrix.
#'   Matrix of dependent variables (Y).
#' @param X Numeric matrix.
#'   Matrix of predictors (X).
#'
#' @return Matrix of estimated autoregressive
#'   and cross-regression coefficients.
#'
#' @examples
#' Y <- dat_p2_yx$Y
#' X <- dat_p2_yx$X
#' FitVAROLS(Y = Y, X = X)
#'
#' @details
#' The [fitAutoReg::FitVAROLS()] function estimates the parameters
#' of a Vector Autoregressive (VAR) model
#' using the Ordinary Least Squares (OLS) method.
#' Given the input matrices `Y` and `X`,
#' where `Y` is the matrix of dependent variables,
#' and `X` is the matrix of predictors,
#' the function computes the autoregressive
#' and cross-regression coefficients of the VAR model.
#' Note that if the first column of `X` is a vector of ones,
#' the constant vector is also estimated.
#'
#' The steps involved in estimating the VAR model parameters
#' using OLS are as follows:
#'
#' - Compute the QR decomposition of the lagged predictor matrix `X`
#'   using the `qr_econ` function from the Armadillo library.
#' - Extract the `Q` and `R` matrices from the QR decomposition.
#' - Solve the linear system `R * coef = Q.t() * Y`
#'   to estimate the VAR model coefficients `coef`.
#' - The function returns a matrix containing the estimated
#'   autoregressive and cross-regression coefficients of the VAR model.
#'
#' @family Fitting Autoregressive Model Functions
#' @keywords fitAutoReg fit
#' @export
FitVAROLS <- function(Y, X) {
    .Call(`_fitAutoReg_FitVAROLS`, Y, X)
}

#' Function to generate the sequence of lambdas
#'
#' @author Ivan Jacob Agaloos Pesigan
#'
#' @inheritParams FitVARLasso
#' @param n_lambdas Integer.
#'   Number of lambdas to generate.
#'
#' @return Returns a vector of lambdas.
#'
#' @examples
#' YStd <- StdMat(dat_p2_yx$Y)
#' XStd <- StdMat(dat_p2_yx$X[, -1]) # remove the constant column
#' LambdaSeq(YStd = YStd, XStd = XStd, n_lambdas = 100)
#'
#' @family Fitting Autoregressive Model Functions
#' @keywords fitAutoReg fit
#' @export
LambdaSeq <- function(YStd, XStd, n_lambdas) {
    .Call(`_fitAutoReg_LambdaSeq`, YStd, XStd, n_lambdas)
}

#' Return Standardized Estimates to the Original Scale
#'
#' @author Ivan Jacob Agaloos Pesigan
#'
#' @param coef_std Numeric matrix.
#'   Standardized estimates of the autoregression
#'   and cross regression coefficients.
#' @param Y Numeric matrix.
#'   Matrix of dependent variables (Y).
#' @param X Numeric matrix.
#'   Matrix of predictors (X).
#'
#' @examples
#' Y <- dat_p2_yx$Y
#' X <- dat_p2_yx$X[, -1] # remove the constant column
#' YStd <- StdMat(Y)
#' XStd <- StdMat(X)
#' coef_std <- FitVAROLS(Y = YStd, X = XStd)
#' FitVAROLS(Y = Y, X = X)
#' OrigScale(coef_std = coef_std, Y = Y, X = X)
#'
#' @family Fitting Autoregressive Model Functions
#' @keywords fitAutoReg utils
#' @export
OrigScale <- function(coef_std, Y, X) {
    .Call(`_fitAutoReg_OrigScale`, coef_std, Y, X)
}

#' Parametric Bootstrap for the Vector Autoregressive Model
#' with Exogenous Variables
#' Using Lasso Regularization
#'
#' @author Ivan Jacob Agaloos Pesigan
#'
#' @inheritParams PBootVARLasso
#' @inheritParams PBootVARExoOLS
#'
#' @return List with the following elements:
#'   - **est**: Numeric matrix.
#'     Original OLS estimate of the coefficient matrix.
#'   - **boot**: Numeric matrix.
#'     Matrix of vectorized bootstrap estimates of the coefficient matrix.
#'
#' @examples
#' data <- dat_p2_exo$data
#' exo_mat <- dat_p2_exo$exo_mat
#' pb <- PBootVARExoLasso(
#'   data = data,
#'   exo_mat = exo_mat,
#'   p = 2,
#'   B = 5,
#'   burn_in = 0,
#'   n_lambdas = 10,
#'   crit = "ebic",
#'   max_iter = 1000,
#'   tol = 1e-5
#' )
#' str(pb)
#'
#' @family Fitting Autoregressive Model Functions
#' @keywords fitAutoReg pb
#' @export
PBootVARExoLasso <- function(data, exo_mat, p, B, burn_in, n_lambdas, crit, max_iter, tol) {
    .Call(`_fitAutoReg_PBootVARExoLasso`, data, exo_mat, p, B, burn_in, n_lambdas, crit, max_iter, tol)
}

#' Parametric Bootstrap for the Vector Autoregressive Model
#' with Exogenous Variables
#' Using Ordinary Least Squares
#'
#' @author Ivan Jacob Agaloos Pesigan
#'
#' @inheritParams PBootVAROLS
#' @inheritParams YXExo
#' @param exo_mat Numeric matrix.
#'   Matrix of exogenous variables with dimensions `t + burn_in` by `m`.
#'   If the number of rows is equal to `t`, set `burn_in = 0`.
#'
#' @return List with the following elements:
#'   - **est**: Numeric matrix.
#'     Original OLS estimate of the coefficient matrix.
#'   - **boot**: Numeric matrix.
#'     Matrix of vectorized bootstrap estimates of the coefficient matrix.
#'
#' @examples
#' data <- dat_p2_exo$data
#' exo_mat <- dat_p2_exo$exo_mat
#' pb <- PBootVARExoOLS(
#'   data = data,
#'   exo_mat = exo_mat,
#'   p = 2,
#'   B = 5,
#'   burn_in = 0
#' )
#' str(pb)
#'
#' @family Fitting Autoregressive Model Functions
#' @keywords fitAutoReg pb
#' @export
PBootVARExoOLS <- function(data, exo_mat, p, B, burn_in) {
    .Call(`_fitAutoReg_PBootVARExoOLS`, data, exo_mat, p, B, burn_in)
}

#' Parametric Bootstrap for the Vector Autoregressive Model
#' Using Lasso Regularization
#'
#' @author Ivan Jacob Agaloos Pesigan
#'
#' @inheritParams PBootVAROLS
#' @inheritParams LambdaSeq
#' @inheritParams FitVARLassoSearch
#'
#' @return List with the following elements:
#'   - **est**: Numeric matrix.
#'     Original Lasso estimate of the coefficient matrix.
#'   - **boot**: Numeric matrix.
#'     Matrix of vectorized bootstrap estimates of the coefficient matrix.
#'
#' @examples
#' pb <- PBootVARLasso(
#'   data = dat_p2,
#'   p = 2,
#'   B = 5,
#'   burn_in = 20,
#'   n_lambdas = 10,
#'   crit = "ebic",
#'   max_iter = 1000,
#'   tol = 1e-5
#' )
#' str(pb)
#'
#' @family Fitting Autoregressive Model Functions
#' @keywords fitAutoReg pb
#' @export
PBootVARLasso <- function(data, p, B, burn_in, n_lambdas, crit, max_iter, tol) {
    .Call(`_fitAutoReg_PBootVARLasso`, data, p, B, burn_in, n_lambdas, crit, max_iter, tol)
}

#' Parametric Bootstrap for the Vector Autoregressive Model
#' Using Ordinary Least Squares
#'
#' @author Ivan Jacob Agaloos Pesigan
#'
#' @inheritParams RBootVAROLS
#' @param burn_in Integer.
#'   Number of burn-in observations to exclude before returning the results
#'   in the simulation step.
#'
#' @return List with the following elements:
#'   - **est**: Numeric matrix.
#'     Original OLS estimate of the coefficient matrix.
#'   - **boot**: Numeric matrix.
#'     Matrix of vectorized bootstrap estimates of the coefficient matrix.
#'
#' @examples
#' pb <- PBootVAROLS(data = dat_p2, p = 2, B = 5, burn_in = 20)
#' str(pb)
#'
#' @family Fitting Autoregressive Model Functions
#' @keywords fitAutoReg pb
#' @export
PBootVAROLS <- function(data, p, B, burn_in) {
    .Call(`_fitAutoReg_PBootVAROLS`, data, p, B, burn_in)
}

#' Residual Bootstrap for the Vector Autoregressive Model
#' with Exogenous Variables
#' Using Lasso Regularization
#'
#' @author Ivan Jacob Agaloos Pesigan
#'
#' @inheritParams RBootVARLasso
#' @inheritParams RBootVARExoOLS
#'
#' @return List with the following elements:
#'   - **est**: Numeric matrix.
#'     Original Lasso estimate of the coefficient matrix.
#'   - **boot**: Numeric matrix.
#'     Matrix of vectorized bootstrap estimates of the coefficient matrix.
#'   - **X**: Numeric matrix.
#'     Original `X`
#'   - **Y**: List of numeric matrices.
#'     Bootstrapped `Y`
#'
#' @examples
#' data <- dat_p2_exo$data
#' exo_mat <- dat_p2_exo$exo_mat
#' rb <- RBootVARExoLasso(
#'   data = data,
#'   exo_mat = exo_mat,
#'   p = 2,
#'   B = 5,
#'   n_lambdas = 10,
#'   crit = "ebic",
#'   max_iter = 1000,
#'   tol = 1e-5
#' )
#' str(rb)
#'
#' @family Fitting Autoregressive Model Functions
#' @keywords fitAutoReg rb
#' @export
RBootVARExoLasso <- function(data, exo_mat, p, B, n_lambdas, crit, max_iter, tol) {
    .Call(`_fitAutoReg_RBootVARExoLasso`, data, exo_mat, p, B, n_lambdas, crit, max_iter, tol)
}

#' Residual Bootstrap for the Vector Autoregressive Model
#' with Exogenous Variables
#' Using Ordinary Least Squares
#'
#' @author Ivan Jacob Agaloos Pesigan
#'
#' @inheritParams RBootVAROLS
#' @param exo_mat Numeric matrix.
#'   Matrix of exogenous variables with dimensions `t` by `m`.
#'
#' @return List with the following elements:
#'   - **est**: Numeric matrix.
#'     Original OLS estimate of the coefficient matrix.
#'   - **boot**: Numeric matrix.
#'     Matrix of vectorized bootstrap estimates of the coefficient matrix.
#'   - **X**: Numeric matrix.
#'     Original `X`
#'   - **Y**: List of numeric matrices.
#'     Bootstrapped `Y`
#'
#' @examples
#' data <- dat_p2_exo$data
#' exo_mat <- dat_p2_exo$exo_mat
#' rb <- RBootVARExoOLS(data = data, exo_mat = exo_mat, p = 2, B = 5)
#' str(rb)
#'
#' @family Fitting Autoregressive Model Functions
#' @keywords fitAutoReg rb
#' @export
RBootVARExoOLS <- function(data, exo_mat, p, B) {
    .Call(`_fitAutoReg_RBootVARExoOLS`, data, exo_mat, p, B)
}

#' Residual Bootstrap for the Vector Autoregressive Model
#' Using Lasso Regularization
#'
#' @author Ivan Jacob Agaloos Pesigan
#'
#' @inheritParams RBootVAROLS
#' @inheritParams FitVARLassoSearch
#' @inheritParams LambdaSeq
#'
#' @return List with the following elements:
#'   - **est**: Numeric matrix.
#'     Original Lasso estimate of the coefficient matrix.
#'   - **boot**: Numeric matrix.
#'     Matrix of vectorized bootstrap estimates of the coefficient matrix.
#'   - **X**: Numeric matrix.
#'     Original `X`
#'   - **Y**: List of numeric matrices.
#'     Bootstrapped `Y`
#'
#' @examples
#' rb <- RBootVARLasso(
#'   data = dat_p2,
#'   p = 2,
#'   B = 5,
#'   n_lambdas = 10,
#'   crit = "ebic",
#'   max_iter = 1000,
#'   tol = 1e-5
#' )
#' str(rb)
#'
#' @family Fitting Autoregressive Model Functions
#' @keywords fitAutoReg rb
#' @export
RBootVARLasso <- function(data, p, B, n_lambdas, crit, max_iter, tol) {
    .Call(`_fitAutoReg_RBootVARLasso`, data, p, B, n_lambdas, crit, max_iter, tol)
}

#' Residual Bootstrap for the Vector Autoregressive Model
#' Using Ordinary Least Squares
#'
#' @author Ivan Jacob Agaloos Pesigan
#'
#' @inheritParams YX
#' @param B Integer.
#'   Number of bootstrap samples to generate.
#'
#' @return List with the following elements:
#'   - **est**: Numeric matrix.
#'     Original OLS estimate of the coefficient matrix.
#'   - **boot**: Numeric matrix.
#'     Matrix of vectorized bootstrap estimates of the coefficient matrix.
#'   - **X**: Numeric matrix.
#'     Original `X`
#'   - **Y**: List of numeric matrices.
#'     Bootstrapped `Y`
#'
#' @examples
#' rb <- RBootVAROLS(data = dat_p2, p = 2, B = 5)
#' str(rb)
#'
#' @family Fitting Autoregressive Model Functions
#' @keywords fitAutoReg rb
#' @export
RBootVAROLS <- function(data, p, B) {
    .Call(`_fitAutoReg_RBootVAROLS`, data, p, B)
}

#' Compute AIC, BIC, and EBIC for Lasso Regularization
#'
#' This function computes the Akaike Information Criterion (AIC),
#' Bayesian Information Criterion (BIC),
#' and Extended Bayesian Information Criterion (EBIC)
#' for a given matrix of predictors `X`, a matrix of outcomes `Y`,
#' and a vector of lambda hyperparameters for Lasso regularization.
#'
#' @author Ivan Jacob Agaloos Pesigan
#'
#' @inheritParams FitVARLassoSearch
#'
#' @return List with the following elements:
#'   - **criteria**: Matrix with columns for
#'     lambda, AIC, BIC, and EBIC values.
#'   - **fit**: List of matrices containing
#'     the estimated autoregressive
#'     and cross-regression coefficients for each lambda.
#'
#' @examples
#' YStd <- StdMat(dat_p2_yx$Y)
#' XStd <- StdMat(dat_p2_yx$X[, -1])
#' lambdas <- 10^seq(-5, 5, length.out = 100)
#' search <- SearchVARLasso(YStd = YStd, XStd = XStd, lambdas = lambdas,
#'   max_iter = 10000, tol = 1e-5)
#' plot(x = 1:nrow(search$criteria), y = search$criteria[, 4],
#'   type = "b", xlab = "lambda", ylab = "EBIC")
#'
#' @family Fitting Autoregressive Model Functions
#' @keywords fitAutoReg fit
#' @export
SearchVARLasso <- function(YStd, XStd, lambdas, max_iter, tol) {
    .Call(`_fitAutoReg_SearchVARLasso`, YStd, XStd, lambdas, max_iter, tol)
}

#' Standardize Matrix
#'
#' This function standardizes the given matrix by centering the columns
#' and scaling them to have unit variance.
#'
#' @author Ivan Jacob Agaloos Pesigan
#'
#' @param X Numeric matrix.
#'   The matrix to be standardized.
#'
#' @return Numeric matrix with standardized values.
#'
#' @examples
#' std <- StdMat(dat_p2)
#' colMeans(std)
#' var(std)
#'
#' @family Fitting Autoregressive Model Functions
#' @keywords fitAutoReg utils
#' @export
StdMat <- function(X) {
    .Call(`_fitAutoReg_StdMat`, X)
}

#' Simulate Data from a Vector Autoregressive (VAR) Model with Exogenous
#' Variables
#'
#' This function generates synthetic time series data
#' from a Vector Autoregressive (VAR) model with exogenous variables.
#'
#' @author Ivan Jacob Agaloos Pesigan
#'
#' @param time Integer.
#'   Number of time points to simulate.
#' @param burn_in Integer.
#'   Number of burn-in observations to exclude before returning the results.
#' @param constant Numeric vector.
#'   The constant term vector of length `k`,
#'   where `k` is the number of variables.
#' @param coef Numeric matrix.
#'   Coefficient matrix with dimensions `k` by `(k * p)`.
#'   Each `k` by `k` block corresponds to the coefficient matrix
#'   for a particular lag.
#' @param chol_cov Numeric matrix.
#'   The Cholesky decomposition of the covariance matrix
#'   of the multivariate normal noise.
#'   It should have dimensions `k` by `k`.
#' @param exo_mat Numeric matrix.
#'   Matrix of exogenous covariates with dimensions `time + burn_in` by `x`.
#'   Each column corresponds to a different exogenous variable.
#' @param exo_coef Numeric vector.
#'   Coefficient matrix with dimensions `k` by `x`
#'   associated with the exogenous covariates.
#'
#' @examples
#' set.seed(42)
#' time <- 1000L
#' burn_in <- 200
#' k <- 3
#' p <- 2
#' constant <- c(1, 1, 1)
#' coef <- matrix(
#'   data = c(
#'     0.4, 0.0, 0.0, 0.1, 0.0, 0.0,
#'     0.0, 0.5, 0.0, 0.0, 0.2, 0.0,
#'     0.0, 0.0, 0.6, 0.0, 0.0, 0.3
#'   ),
#'   nrow = k,
#'   byrow = TRUE
#' )
#' chol_cov <- chol(diag(3))
#' exo_mat <- MASS::mvrnorm(
#'   n = time + burn_in,
#'   mu = c(0, 0, 0),
#'   Sigma = diag(3)
#' )
#' exo_coef <- matrix(
#'   data = c(
#'     0.5, 0.0, 0.0,
#'     0.0, 0.5, 0.0,
#'     0.0, 0.0, 0.5
#'   ),
#'   nrow = 3
#' )
#' y <- SimVARExo(
#'   time = time,
#'   burn_in = burn_in,
#'   constant = constant,
#'   coef = coef,
#'   chol_cov = chol_cov,
#'   exo_mat = exo_mat,
#'   exo_coef = exo_coef
#' )
#' str(y)
#'
#' @return Numeric matrix containing the simulated time series data
#'   with dimensions `k` by `time`,
#'   where `k` is the number of variables and
#'   `time` is the number of observations.
#'
#' @family Simulation of Autoregressive Data Functions
#' @keywords simAutoReg sim data var
#' @export
SimVARExo <- function(time, burn_in, constant, coef, chol_cov, exo_mat, exo_coef) {
    .Call(`_fitAutoReg_SimVARExo`, time, burn_in, constant, coef, chol_cov, exo_mat, exo_coef)
}

#' Simulate Data from a Vector Autoregressive (VAR) Model
#'
#' This function generates synthetic time series data
#' from a Vector Autoregressive (VAR) model.
#'
#' @author Ivan Jacob Agaloos Pesigan
#'
#' @param time Integer.
#'   Number of time points to simulate.
#' @param burn_in Integer.
#'   Number of burn-in observations to exclude before returning the results.
#' @param constant Numeric vector.
#'   The constant term vector of length `k`,
#'   where `k` is the number of variables.
#' @param coef Numeric matrix.
#'   Coefficient matrix with dimensions `k` by `(k * p)`.
#'   Each `k` by `k` block corresponds to the coefficient matrix
#'   for a particular lag.
#' @param chol_cov Numeric matrix.
#'   The Cholesky decomposition of the covariance matrix
#'   of the multivariate normal noise.
#'   It should have dimensions `k` by `k`.
#'
#' @return Numeric matrix containing the simulated time series data
#'   with dimensions `k` by `time`,
#'   where `k` is the number of variables and
#'   `time` is the number of observations.
#'
#' @examples
#' set.seed(42)
#' time <- 50L
#' burn_in <- 10L
#' k <- 3
#' p <- 2
#' constant <- c(1, 1, 1)
#' coef <- matrix(
#'   data = c(
#'     0.4, 0.0, 0.0, 0.1, 0.0, 0.0,
#'     0.0, 0.5, 0.0, 0.0, 0.2, 0.0,
#'     0.0, 0.0, 0.6, 0.0, 0.0, 0.3
#'   ),
#'   nrow = k,
#'   byrow = TRUE
#' )
#' chol_cov <- chol(diag(3))
#' y <- SimVAR(
#'   time = time,
#'   burn_in = burn_in,
#'   constant = constant,
#'   coef = coef,
#'   chol_cov = chol_cov
#' )
#' head(y)
#'
#' @details
#' The [SimVAR()] function generates synthetic time series data
#' from a Vector Autoregressive (VAR) model.
#' The VAR model is defined by the constant term `constant`,
#' the coefficient matrix `coef`,
#' and the Cholesky decomposition of the covariance matrix
#' of the multivariate normal process noise `chol_cov`.
#' The generated time series data follows a VAR(p) process,
#' where `p` is the number of lags specified by the size of `coef`.
#' The generated data includes a burn-in period,
#' which is excluded before returning the results.
#'
#' The steps involved in generating the VAR time series data are as follows:
#'
#' - Extract the number of variables `k` and the number of lags `p`
#'   from the input.
#' - Create a matrix `data` of size `k` by (`time + burn_in`)
#'   to store the generated VAR time series data.
#' - Set the initial values of the matrix `data`
#'   using the constant term `constant`.
#' - For each time point starting from the `p`-th time point
#'   to `time + burn_in - 1`:
#'   * Generate a vector of random noise
#'     from a multivariate normal distribution
#'     with mean 0 and covariance matrix `chol_cov`.
#'   * Generate the VAR time series values for each variable `j` at time `t`
#'     using the formula:
#'     \deqn{
#'       Y_{tj} = \mathrm{constant}_j +
#'       \sum_{l = 1}^{p} \sum_{m = 1}^{k} (\mathrm{coef}_{jm} * Y_{im}) +
#'       \mathrm{noise}_{j}
#'     }
#'     where \eqn{Y_{tj}} is the value of variable `j` at time `t`,
#'     \eqn{\mathrm{constant}_j} is the constant term for variable `j`,
#'     \eqn{\mathrm{coef}_{jm}} are the coefficients for variable `j`
#'     from lagged variables up to order `p`,
#'     \eqn{Y_{tm}} are the lagged values of variable `m`
#'     up to order `p` at time `t`,
#'     and \eqn{\mathrm{noise}_{j}} is the element `j`
#'     from the generated vector of random process noise.
#' - Transpose the matrix `data` and return only
#'   the required time period after the burn-in period,
#'   which is from column `burn_in` to column `time + burn_in - 1`.
#'
#' @family Simulation of Autoregressive Data Functions
#' @keywords simAutoReg sim data var
#' @export
SimVAR <- function(time, burn_in, constant, coef, chol_cov) {
    .Call(`_fitAutoReg_SimVAR`, time, burn_in, constant, coef, chol_cov)
}

#' Create Y and X Matrices with Exogenous Variables
#'
#' This function creates the dependent variable (Y)
#' and predictor variable (X) matrices.
#'
#' @author Ivan Jacob Agaloos Pesigan
#'
#' @param data Numeric matrix.
#'   The time series data with dimensions `t` by `k`,
#'   where `t` is the number of observations
#'   and `k` is the number of variables.
#' @param p Integer.
#'   The order of the VAR model (number of lags).
#' @param exo_mat Numeric matrix.
#'   Matrix of exogenous variables with dimensions `t` by `m`.
#'
#' @return List containing the dependent variable (Y)
#' and predictor variable (X) matrices.
#' Note that the resulting matrices will have `t - p` rows.
#'
#' @examples
#' set.seed(42)
#' time <- 1000L
#' burn_in <- 200
#' k <- 3
#' p <- 2
#' constant <- c(1, 1, 1)
#' coef <- matrix(
#'   data = c(
#'     0.4, 0.0, 0.0, 0.1, 0.0, 0.0,
#'     0.0, 0.5, 0.0, 0.0, 0.2, 0.0,
#'     0.0, 0.0, 0.6, 0.0, 0.0, 0.3
#'   ),
#'   nrow = k,
#'   byrow = TRUE
#' )
#' chol_cov <- chol(diag(3))
#' exo_mat <- MASS::mvrnorm(
#'   n = time + burn_in,
#'   mu = c(0, 0, 0),
#'   Sigma = diag(3)
#' )
#' exo_coef <- matrix(
#'   data = c(
#'     0.5, 0.0, 0.0,
#'     0.0, 0.5, 0.0,
#'     0.0, 0.0, 0.5
#'   ),
#'   nrow = 3
#' )
#' y <- SimVARExo(
#'   time = time,
#'   burn_in = burn_in,
#'   constant = constant,
#'   coef = coef,
#'   chol_cov = chol_cov,
#'   exo_mat = exo_mat,
#'   exo_coef = exo_coef
#' )
#' yx <- YXExo(
#'   data = y,
#'   p = 2,
#'   exo_mat = exo_mat[(burn_in + 1):(time + burn_in), ]
#' )
#' str(yx)
#'
#' @details
#' The [YX()] function creates the `Y` and `X` matrices
#' required for fitting a Vector Autoregressive (VAR) model.
#' Given the input `data` matrix with dimensions `t` by `k`,
#' where `t` is the number of observations and `k` is the number of variables,
#' and the order of the VAR model `p` (number of lags),
#' the function constructs lagged predictor matrix `X`
#' and the dependent variable matrix `Y`.
#'
#' The steps involved in creating the `Y` and `X` matrices are as follows:
#'
#' - Determine the number of observations `t` and the number of variables `k`
#'   from the input data matrix.
#' - Create matrices `X` and `Y` to store lagged variables
#'   and the dependent variable, respectively.
#' - Populate the matrices `X` and `Y` with the appropriate lagged data.
#'   The predictors matrix `X` contains a column of ones
#'   and the lagged values of the dependent variables,
#'   while the dependent variable matrix `Y` contains the original values
#'   of the dependent variables.
#' - The function returns a list containing the `Y` and `X` matrices,
#'   which can be used for further analysis and estimation
#'   of the VAR model parameters.
#'
#' @seealso
#' The [SimVAR()] function for simulating time series data
#' from a VAR model.
#'
#' @family Simulation of Autoregressive Data Functions
#' @keywords simAutoReg utils
#' @export
YXExo <- function(data, p, exo_mat) {
    .Call(`_fitAutoReg_YXExo`, data, p, exo_mat)
}

#' Create Y and X Matrices
#'
#' This function creates the dependent variable (Y)
#' and predictor variable (X) matrices.
#'
#' @author Ivan Jacob Agaloos Pesigan
#'
#' @param data Numeric matrix.
#'   The time series data with dimensions `t` by `k`,
#'   where `t` is the number of observations
#'   and `k` is the number of variables.
#' @param p Integer.
#'   The order of the VAR model (number of lags).
#'
#' @return List containing the dependent variable (Y)
#' and predictor variable (X) matrices.
#' Note that the resulting matrices will have `t - p` rows.
#'
#' @examples
#' set.seed(42)
#' time <- 50L
#' burn_in <- 10L
#' k <- 3
#' p <- 2
#' constant <- c(1, 1, 1)
#' coef <- matrix(
#'   data = c(
#'     0.4, 0.0, 0.0, 0.1, 0.0, 0.0,
#'     0.0, 0.5, 0.0, 0.0, 0.2, 0.0,
#'     0.0, 0.0, 0.6, 0.0, 0.0, 0.3
#'   ),
#'   nrow = k,
#'   byrow = TRUE
#' )
#' chol_cov <- chol(diag(3))
#' y <- SimVAR(
#'   time = time,
#'   burn_in = burn_in,
#'   constant = constant,
#'   coef = coef,
#'   chol_cov = chol_cov
#' )
#' yx <- YX(data = y, p = 2)
#' str(yx)
#'
#' @details
#' The [YX()] function creates the `Y` and `X` matrices
#' required for fitting a Vector Autoregressive (VAR) model.
#' Given the input `data` matrix with dimensions `t` by `k`,
#' where `t` is the number of observations and `k` is the number of variables,
#' and the order of the VAR model `p` (number of lags),
#' the function constructs lagged predictor matrix `X`
#' and the dependent variable matrix `Y`.
#'
#' The steps involved in creating the `Y` and `X` matrices are as follows:
#'
#' - Determine the number of observations `t` and the number of variables `k`
#'   from the input data matrix.
#' - Create matrices `X` and `Y` to store lagged variables
#'   and the dependent variable, respectively.
#' - Populate the matrices `X` and `Y` with the appropriate lagged data.
#'   The predictors matrix `X` contains a column of ones
#'   and the lagged values of the dependent variables,
#'   while the dependent variable matrix `Y` contains the original values
#'   of the dependent variables.
#' - The function returns a list containing the `Y` and `X` matrices,
#'   which can be used for further analysis and estimation
#'   of the VAR model parameters.
#'
#' @seealso
#' The [SimVAR()] function for simulating time series data
#' from a VAR model.
#'
#' @family Simulation of Autoregressive Data Functions
#' @keywords simAutoReg utils
#' @export
YX <- function(data, p) {
    .Call(`_fitAutoReg_YX`, data, p)
}

